### ISSUE TITLE
Subqueries aren't getting named with 'AS'

### ISSUE THREAD

**Issue by davidcinglis** [acioc/Caltech-CS-122#1]
This query fails:

EXPLAIN SELECT \* FROM stores JOIN (SELECT city_id FROM cities WHERE population > 1000000) AS big_cities ON stores.city_id = big_cities.city_id;

The select subquery isn't getting renamed to big_cities, nanodb thinks it is still named cities instead.

**Comment by etsimon** [comment]
relevant post:
https://piazza.com/class/i4iy5e1b1ds4ow?cid=62
